version: 0.2

env:
  variables:
    TEST: "FROM_VARIABLEx"

phases:
  install:
    commands:
      - pwd
      - echo "INSTALL" >> /tmp/artifact.txt
      - git clone https://nrivera-drg:$GITHUB_TOKEN@github.com/dresources/drga-dev-infrastructure-modules.git
      - ls -alF

  build:
    commands:
      - echo "BUILD $TEST" >> /tmp/artifact.txt

  post_build:
    commands:
      - echo "POST BUILD $TEST" >> /tmp/artifact.txt
artifacts:
  files:
    - /tmp/artifact.txt
