version: 0.2

env:
  variables:
    TEST: "FROM_VARIABLEx"

phases:
  install:
    commands:
      - pwd
      - echo "INSTALL" >> /tmp/artifact.txt
      - apt-get update && apt-get -y install jq ssh git
      - git config --global credential.helper 'cache --timeout=600'
      - git config --global  user.name "nrivera-drg"
      - git config --global  user.password $GITHUB_TOKEN
      - cat /root/.gitconfig
      - git --version
      - ls -alF $HOME
      - uname -a
      - printenv
      - ps faux
      - git clone https://github.com/dresources/drga-dev-infrastructure-modules.git

  build:
    commands:
      - echo "BUILD $TEST" >> /tmp/artifact.txt

  post_build:
    commands:
      - echo "POST BUILD $TEST" >> /tmp/artifact.txt
artifacts:
  files:
    - /tmp/artifact.txt
